export type Groom = {
  age: number | null;
  createdAt: Date;
  diet?: "Option1" | null;
  drinkingHabits?: "Option1" | null;
  educationLevel: string | null;
  email: string | null;
  ethnicity: string | null;
  familyDetails: string | null;
  height: number | null;
  hobbies: string | null;
  id: string;
  interests: string | null;
  languageSpoken: string | null;
  location: string | null;
  maritalStatus?: "Option1" | null;
  name: string | null;
  occupation: string | null;
  phoneNumber: string | null;
  religion: string | null;
  smokingHabits?: "Option1" | null;
  updatedAt: Date;
  weight: number | null;
};
