/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { GroomService } from "../groom.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GroomCreateInput } from "./GroomCreateInput";
import { Groom } from "./Groom";
import { GroomFindManyArgs } from "./GroomFindManyArgs";
import { GroomWhereUniqueInput } from "./GroomWhereUniqueInput";
import { GroomUpdateInput } from "./GroomUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GroomControllerBase {
  constructor(
    protected readonly service: GroomService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Groom })
  @nestAccessControl.UseRoles({
    resource: "Groom",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createGroom(@common.Body() data: GroomCreateInput): Promise<Groom> {
    return await this.service.createGroom({
      data: data,
      select: {
        age: true,
        createdAt: true,
        diet: true,
        drinkingHabits: true,
        educationLevel: true,
        email: true,
        ethnicity: true,
        familyDetails: true,
        height: true,
        hobbies: true,
        id: true,
        interests: true,
        languageSpoken: true,
        location: true,
        maritalStatus: true,
        name: true,
        occupation: true,
        phoneNumber: true,
        religion: true,
        smokingHabits: true,
        updatedAt: true,
        weight: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Groom] })
  @ApiNestedQuery(GroomFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Groom",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async grooms(@common.Req() request: Request): Promise<Groom[]> {
    const args = plainToClass(GroomFindManyArgs, request.query);
    return this.service.grooms({
      ...args,
      select: {
        age: true,
        createdAt: true,
        diet: true,
        drinkingHabits: true,
        educationLevel: true,
        email: true,
        ethnicity: true,
        familyDetails: true,
        height: true,
        hobbies: true,
        id: true,
        interests: true,
        languageSpoken: true,
        location: true,
        maritalStatus: true,
        name: true,
        occupation: true,
        phoneNumber: true,
        religion: true,
        smokingHabits: true,
        updatedAt: true,
        weight: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Groom })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Groom",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async groom(
    @common.Param() params: GroomWhereUniqueInput
  ): Promise<Groom | null> {
    const result = await this.service.groom({
      where: params,
      select: {
        age: true,
        createdAt: true,
        diet: true,
        drinkingHabits: true,
        educationLevel: true,
        email: true,
        ethnicity: true,
        familyDetails: true,
        height: true,
        hobbies: true,
        id: true,
        interests: true,
        languageSpoken: true,
        location: true,
        maritalStatus: true,
        name: true,
        occupation: true,
        phoneNumber: true,
        religion: true,
        smokingHabits: true,
        updatedAt: true,
        weight: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Groom })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Groom",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateGroom(
    @common.Param() params: GroomWhereUniqueInput,
    @common.Body() data: GroomUpdateInput
  ): Promise<Groom | null> {
    try {
      return await this.service.updateGroom({
        where: params,
        data: data,
        select: {
          age: true,
          createdAt: true,
          diet: true,
          drinkingHabits: true,
          educationLevel: true,
          email: true,
          ethnicity: true,
          familyDetails: true,
          height: true,
          hobbies: true,
          id: true,
          interests: true,
          languageSpoken: true,
          location: true,
          maritalStatus: true,
          name: true,
          occupation: true,
          phoneNumber: true,
          religion: true,
          smokingHabits: true,
          updatedAt: true,
          weight: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Groom })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Groom",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteGroom(
    @common.Param() params: GroomWhereUniqueInput
  ): Promise<Groom | null> {
    try {
      return await this.service.deleteGroom({
        where: params,
        select: {
          age: true,
          createdAt: true,
          diet: true,
          drinkingHabits: true,
          educationLevel: true,
          email: true,
          ethnicity: true,
          familyDetails: true,
          height: true,
          hobbies: true,
          id: true,
          interests: true,
          languageSpoken: true,
          location: true,
          maritalStatus: true,
          name: true,
          occupation: true,
          phoneNumber: true,
          religion: true,
          smokingHabits: true,
          updatedAt: true,
          weight: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
