/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsInt, IsOptional, IsEnum, IsString, IsNumber } from "class-validator";
import { EnumGroomDiet } from "./EnumGroomDiet";
import { EnumGroomDrinkingHabits } from "./EnumGroomDrinkingHabits";
import { EnumGroomMaritalStatus } from "./EnumGroomMaritalStatus";
import { EnumGroomSmokingHabits } from "./EnumGroomSmokingHabits";

@InputType()
class GroomCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  age?: number | null;

  @ApiProperty({
    required: false,
    enum: EnumGroomDiet,
  })
  @IsEnum(EnumGroomDiet)
  @IsOptional()
  @Field(() => EnumGroomDiet, {
    nullable: true,
  })
  diet?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumGroomDrinkingHabits,
  })
  @IsEnum(EnumGroomDrinkingHabits)
  @IsOptional()
  @Field(() => EnumGroomDrinkingHabits, {
    nullable: true,
  })
  drinkingHabits?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  educationLevel?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  ethnicity?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  familyDetails?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  height?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  hobbies?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  interests?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  languageSpoken?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumGroomMaritalStatus,
  })
  @IsEnum(EnumGroomMaritalStatus)
  @IsOptional()
  @Field(() => EnumGroomMaritalStatus, {
    nullable: true,
  })
  maritalStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  occupation?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  religion?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumGroomSmokingHabits,
  })
  @IsEnum(EnumGroomSmokingHabits)
  @IsOptional()
  @Field(() => EnumGroomSmokingHabits, {
    nullable: true,
  })
  smokingHabits?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  weight?: number | null;
}

export { GroomCreateInput as GroomCreateInput };
